// The node's frame ladder, computed twice — once in Python for the render and
// once in JS for the widget label — must not drift.
//
// This pack's recurring failure is two implementations of one rule. The label
// tells you a blend is worth 12 frames; if the node disagrees, the number on
// screen is a lie and nothing errors. The Python side is generated by
// test_insert_label_fixture.py and checked in, so this runs without torch.
const fs = require("fs");
const GROUP = 17, STARTS = [0, 1, 5, 9, 13];
const framesAtStep = (s) => {
  const q = Math.floor(Math.max(0, s) / 5);
  return q * GROUP + STARTS[Math.max(0, s) % 5];
};
const stepAtFrame = (f) => {
  f = Math.max(0, Math.floor(f));
  const g = Math.floor(f / GROUP), r = f % GROUP;
  let k = 0;
  for (let i = 0; i < STARTS.length; i++) if (STARTS[i] <= r) k = i;
  return g * 5 + k;
};

const want = JSON.parse(fs.readFileSync(__dirname + "/insert_ladder.json", "utf8"));
let bad = 0;
for (const [split, row] of Object.entries(want)) {
  const c = stepAtFrame(Number(split));
  const got = row.map((_, n) =>
    Math.abs(framesAtStep(Math.max(0, c - n)) - framesAtStep(c)));
  if (JSON.stringify(got) !== JSON.stringify(row)) {
    console.log(`  FAIL cut ${split}: label ${got} vs node ${row}`);
    bad++;
  }
}
console.log();
if (bad) { console.log(`${bad} cut(s) disagree`); process.exit(1); }
console.log(`insert label: the widget and the node agree at ${Object.keys(want).length} cuts`);
